"""add is_admin to users

Revision ID: acfa4339a289
Revises: f0d048b1098e
Create Date: 2026-05-15 18:12:24.418041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'acfa4339a289'
down_revision: Union[str, None] = 'f0d048b1098e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default so existing rows get False (autogenerate omits it).
    op.add_column(
        'users',
        sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('users', 'is_admin', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
